name: Docker Test Run
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '36 22 * * 2'
    
jobs:
    - name: Docker Run Job
    runs-on: ubuntu-latest
    steps:
      # Docker Run Action
      - name: Docker Run Action
        uses: mosteo-actions/docker-run@v1
        with:
          image: Dockerfile
         #command: uname -a
         
